### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by olegakbarov** [juliangruber/multilevel-http#20]
got some trashy while installing on OS X
anybody knows what might be wrong?

```
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/leveldown/src/async.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/oleg/code/redux-bp/node_modules/leveldown
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:leveldown@0.1.4 leveldown@0.1.4 install: `node-gyp rebuild`
npm WARN install:leveldown@0.1.4 Exit status 1
```

**Comment by juliangruber** [comment]
the error seems to be related to leveldown, please create an issue with the _full_ npm install output here: https://github.com/Level/leveldown/issues/new

**Comment by olegakbarov** [comment]
Okay, thank you.

**Comment by eskalera** [comment]
@olegakbarov, have you found any solution to this issue?

**Comment by olegakbarov** [comment]
@eskalera Unfortunately, no.

**Comment by eskalera** [comment]
Shame @olegakbarov... thanks for answering though. Any other alternative either? I've bee searching for a couple of days but I couldn't find any decent cmd nor gui leveldb client. For now I've implemented my own express routes to manage leveldb.

**Comment by juliangruber** [comment]
@eskalera you should check out npm.im/multilevel
