### ISSUE TITLE
readStream bug

### ISSUE THREAD

**Issue by alessioalex** [juliangruber/multilevel-http#8]
I'm using the default 'utf8' encoding for values. Will debug this more and provide further details:

``` js
net.js:612
    throw new TypeError('invalid data');
          ^
TypeError: invalid data
    at WriteStream.Socket.write (net.js:612:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:106:17)
    at Array.forEach (native)
    at Stream.<anonymous> (/Users/alexandruvladutu/www/multilevel-http/lib/client.js:108:9)
    at Stream.stream.write (/Users/alexandruvladutu/www/multilevel-http/node_modules/through/index.js:25:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at Parser.parser.onToken (/Users/alexandruvladutu/www/multilevel-http/node_modules/JSONStream/index.js:62:18)
    at Parser.proto.write (/Users/alexandruvladutu/www/multilevel-http/node_modules/JSONStream/node_modules/jsonparse/jsonparse.js:98:34)
```

**Comment by alessioalex** [comment]
nevermind I can't replicate this, maybe I did something wrong. closing it for now

**Comment by alessioalex** [comment]
ah yes, I was doing `createReadStream().pipe(process.stdout)` :)
